backend: # Required
  name: git-gateway
  branch: main
media_folder: "src/assets/images" # Required
public_folder: "assets/images" # Required
collections: # Required. Accepts a list of collection objects
  - name: "pages" # Required. Used in routes
    label: "Pages" # Required. Used in the UI
    folder: "src" # Required. The path to the folder where the documents are stored
    extension: "liquid" # The file extension for the documents
    format: "frontmatter" # Required. The format used by the documents
    create: true # Important. Allow users to create new documents in this collection
    fields: # Required. The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"} # Required
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "base"}
      - {label: "Tags", name: "tags", widget: "string"}
      - {label: "Texte navigation", name: "navTexte", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"} # Required
  - label: "Settings"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Frameworks"
        name: "frameworks"
        file: "src/_data/frameworks.json"
        fields:
          - label: "CSS Frameworks"
            name: "items"
            widget: "list"
            allow_add: true
            collapsed: true
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Type", name: "type", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }
              - { label: "Version", name: "version", widget: "string" }
              - { label: "GitHub", name: "github", widget: "string" }
              - { label: "Stars", name: "stars", widget: "number" }
              - { label: "Published", name: "published", widget: "string" }
              - { label: "Documentation", name: "doc", widget: "string" }
              - { label: "Demo", name: "demo", widget: "string" }
              - { label: "NPM", name: "npm", widget: "string" }
              - { label: "CDN", name: "cdn", widget: "string" }
              - { label: "Sass", name: "sass", widget: "boolean" }
              - { label: "Published", name: "published", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }
              - { label: "Responsive", name: "responsive", widget: "boolean" }
              - { label: "Components", name: "Components", widget: "boolean" }
              - { name: "variables", widget: "boolean" }
