backend: # Required
  name: git-gateway
  branch: main
media_folder: "src/assets/images" # Required
public_folder: "assets/images" # Required
collections: # Required. Accepts a list of collection objects
  - name: "pages" # Required. Used in routes
    label: "Pages" # Required. Used in the UI
    folder: "src" # Required. The path to the folder where the documents are stored
    create: true # Important. Allow users to create new documents in this collection
    fields: # Required. The fields for each document, usually in front matter
      - {name: "title"} # Required
      - {name: "description"}
      - {name: "date", widget: "datetime"}
      - {name: "layout", widget: "hidden", default: "base"}
      - {name: "tags"}
      - {name: "navTexte"}
      - {name: "body"} # Required
  - label: "Settings"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Frameworks"
        name: "frameworks"
        file: "src/_data/frameworks.json"
        fields:
          - label: "CSS Frameworks"
            name: "items"
            widget: "list"
            allow_add: true
            collapsed: true
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Type", name: "type", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }
              - { label: "Version", name: "version", widget: "string" }
              - { label: "GitHub", name: "github", widget: "string" }
              - { label: "Stars", name: "stars", widget: "number" }
              - { label: "Type", name: "type", widget: "string" }
              - { label: "Published", name: "published", widget: "string" }
              - { label: "Documentation", name: "doc", widget: "string" }
              - { label: "Demo", name: "demo", widget: "string" }
              - { label: "NPM", name: "npm", widget: "string" }
